### ISSUE TITLE
Centos 7 Project make error: cannot execute TextTransform.exe.

### ISSUE THREAD

**Issue by MrJeffyw** [Sysinternals/SysmonForLinux#35]
[root@hunter-0003 build]# make
[  0%] Built target sysmonEBPFkern5.6-
[  0%] Built target sysmonEBPFkern5.3-5.5
[  1%] Extracting sysmonmsg.mc.utf16
/usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe: /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe: cannot execute binary file
make[2]: *** [sysmonmsg.mc.utf16] Error 126
make[1]: *** [CMakeFiles/sysmonLogView.dir/all] Error 2
make: *** [all] Error 2

Please help

**Comment by tank-trax** [comment]
same here on Linux Mint 20.2 Uma

```
make
[  1%] Extracting sysmonmsg.mc.utf16
make[2]: /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe: Command not found
make[2]: *** [CMakeFiles/sysmonLogView.dir/build.make:94: sysmonmsg.mc.utf16] Error 127
make[1]: *** [CMakeFiles/Makefile2:123: CMakeFiles/sysmonLogView.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by tank-trax** [comment]
following the instructions to install [monodevelop](https://www.monodevelop.com/download/#fndtn-download-lin) resolved that error

then got this...

```
[ 19%] Packing manifest.xml into manifest.xml.o
make[2]: *** No rule to make target '/opt/sysinternalsEBPF/ebpfKern/sysinternalsEBPF_helpers.c', needed by 'sysmonEBPFkern4.15.o'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:232: CMakeFiles/sysmon.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
which was resolved by installed [SysinternalsEBPF](https://github.com/Sysinternals/SysinternalsEBPF) and libgmock-dev

**Comment by kesheldr** [comment]
@tank-trax Can you confirm it builds correctly?
@MrJeffyw Are you still having issues? If so, please let me know which distro/version you are using. Thanks.

**Comment by MrJeffyw** [comment]
@kesheldr I still having issues.
I tired to rebuild on  centos-release-7-9.2009.1.el7.centos.x86_64. After following the instructions to install [monodevelop](https://www.monodevelop.com/download/#fndtn-download-lin-centos), i got the error:

[  2%] Built target checkEBPFsizes
[  3%] Extracting sysmonmsgop.man.utf16
make[2]: execvp: /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe: Permission denied
make[2]: *** [sysmonmsgop.man.utf16] Error 127
make[1]: *** [CMakeFiles/sysmonLogView.dir/all] Error 2
make: *** [all] Error 2

**Comment by MrJeffyw** [comment]
> @kesheldr I still having issues. I tired to rebuild on centos-release-7-9.2009.1.el7.centos.x86_64. After following the instructions to install [monodevelop](https://www.monodevelop.com/download/#fndtn-download-lin-centos), i got the error:
> 
> [ 2%] Built target checkEBPFsizes [ 3%] Extracting sysmonmsgop.man.utf16 make[2]: execvp: /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe: Permission denied make[2]: *** [sysmonmsgop.man.utf16] Error 127 make[1]: *** [CMakeFiles/sysmonLogView.dir/all] Error 2 make: *** [all] Error 2

------------------------------------------------------------------------------------------------------------------------------
Hi kesheldr, I tired to build SysinternalsEBPF firstly. Then got the following error.

[ 21%] Building C object CMakeFiles/sysinternalsEBPF.dir/telemetryLoader.c.o
/root/SysinternalsEBPF/telemetryLoader.c: In function ‘connectRawSock’:
/root/SysinternalsEBPF/telemetryLoader.c:430:41: error: ‘SO_ATTACH_BPF’ undeclared (first use in this function)
     if (setsockopt(rawSock, SOL_SOCKET, SO_ATTACH_BPF, &rawProgFd, sizeof(rawProgFd)) < 0) {
                                         ^
/root/SysinternalsEBPF/telemetryLoader.c:430:41: note: each undeclared identifier is reported only once for each function it appears in
/root/SysinternalsEBPF/telemetryLoader.c: In function ‘getKernelVersion’:
/root/SysinternalsEBPF/telemetryLoader.c:561:12: error: missing braces around initializer [-Werror=missing-braces]
     struct utsname              unameStruct = { 0 };
            ^
/root/SysinternalsEBPF/telemetryLoader.c:561:12: error: (near initialization for ‘unameStruct.sysname’) [-Werror=missing-braces]
/root/SysinternalsEBPF/telemetryLoader.c: In function ‘getObjectAndPath’:
/root/SysinternalsEBPF/telemetryLoader.c:601:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned int i=0; i<ebpfConfig->numEBPFobjects; i++) {
     ^
/root/SysinternalsEBPF/telemetryLoader.c:601:5: note: use option -std=c99 or -std=gnu99 to compile your code
/root/SysinternalsEBPF/telemetryLoader.c:618:23: error: redefinition of ‘i’
     for (unsigned int i=0; i<ebpfConfig->numDefaultPaths; i++) {
                       ^
/root/SysinternalsEBPF/telemetryLoader.c:601:23: note: previous definition of ‘i’ was here
     for (unsigned int i=0; i<ebpfConfig->numEBPFobjects; i++) {
                       ^
/root/SysinternalsEBPF/telemetryLoader.c:618:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned int i=0; i<ebpfConfig->numDefaultPaths; i++) {
     ^
/root/SysinternalsEBPF/telemetryLoader.c: In function ‘locateTPprogs’:
/root/SysinternalsEBPF/telemetryLoader.c:694:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (unsigned int n=0; n<7; n++) {
             ^
/root/SysinternalsEBPF/telemetryLoader.c: In function ‘linkTPprogs’:
/root/SysinternalsEBPF/telemetryLoader.c:912:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (unsigned int syscall=0; syscall<=SYSCALL_MAX; syscall++) {
             ^
/root/SysinternalsEBPF/telemetryLoader.c:935:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (unsigned int syscall=0; syscall<=SYSCALL_MAX; syscall++) {
             ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/sysinternalsEBPF.dir/telemetryLoader.c.o] Error 1
make[1]: *** [CMakeFiles/sysinternalsEBPF.dir/all] Error 2
make: *** [all] Error 2

**Comment by kesheldr** [comment]
Hello @MrJeffyw. Unfortunately, I don't think you'll be overly successful with Centos 7. I don't know why mono doesn't seem to work (without investigation, I might add), and I could fix the c99 errors by either modifying the source or modifying the CMakeLists.txt file, but I'm concerned that setsockopt() doesn't know about SO_ATTACH_BPF.
On top of all that, if you're running a kernel <4.15 (I believe Centos 7 is on v3.10) then Sysmon will refuse to run, at least until I've investigated what eBPF functionality RedHat/Centos back-ported to earlier kernels and what needs to be done to make it work.
This is certainly on the ToDo list and will be addressed, but it won't happen immediately.

**Comment by kesheldr** [comment]
Hello @MrJeffyw, a recent fix from @mxatone fixed the execution of TextTransform.exe by explicitly using mono to run it ('mono TextTransform.exe' rather than 'TextTransform.exe'). I've also pushed a change so it won't have all those non-C99 errors. I can't fix the SO_ATTACH_BPF problem however as I believe that is due to either an old libc or an old kernel. I'm sorry, but I'll have to close this.
